"""English messages. Option-style strings must stay aligned with the zh catalog keys."""

MESSAGES = {
    # ─── Language selection (shown bilingual, identical in both catalogs) ───
    "lang.saved_zh": "已设置语言：中文",
    "lang.saved_en": "Language set to: English",

    # ─── First-run wizard ───
    "firstrun.panel": "[bold]ChCode[/bold] — Terminal AI coding assistant\n\nFirst run requires configuring an AI model connection.\nSet environment variables for auto-detection (recommended), or fill in manually.",
    "firstrun.select_method": "Select configuration method:",
    "firstrun.env_detected": "{name} (detected {env_var})",
    "firstrun.modelscope_quick": "ModelScope quick setup...",
    "firstrun.manual": "Manual setup...",
    "firstrun.exit": "Exit",
    "firstrun.exit_hint": "Set environment variables and rerun, or run 'chcode config new' to configure manually",
    "firstrun.no_env_key": "No API keys detected in environment variables",
    "firstrun.select": "Select:",
    "firstrun.env_hint": "Tip: set an API key in environment variables and rerun, for example:",
    "firstrun.env_example": "  set BIGMODEL_API_KEY=your_key",
    "firstrun.manual_cmd_hint": "or run 'chcode config new' to configure manually",
    "firstrun.config_done": "Configuration complete: {model}",

    # ─── Model configuration ───
    "model.method_select": "Configuration method:",
    "model.context_length": "Context length (tokens, default 1M):",
    "model.saved": "Model configuration saved: {model}",
    "model.multimodal_ask": "Is this a multimodal (vision) model?",
    "model.vision_added_default": "Added to vision model list (default): {model} (images processed directly, vision tool disabled)",
    "model.vision_added_fallback": "Added to vision model list (fallback): {model} (images processed directly, vision tool disabled)",
    "model.vision_duplicate": "Not written to vision config (identical config already exists)",
    "model.vision_failed": "Vision model configuration failed (does not affect main config): {error}",
    "model.edit_none": "No current model configuration, please create one",
    "model.updated": "Model configuration updated: {model}",
    "model.switch_no_default": "Please configure a default model first",
    "model.switch_no_fallback": "No fallback models available to switch",
    "model.current_default_tag": " (current default)",
    "model.select_to_use": "Select a model to use:",
    "model.switch_confirm": "Confirm switch to {model}? Current default will move to fallback list",
    "model.switched": "Switched to: {model}",

    # ─── ModelScope quick setup ───
    "modelscope.testing": "Testing connection...",
    "modelscope.connect_failed": "Connection test failed: {detail}",
    "modelscope.config_done": "Configuration complete: {model} (default)",
    "modelscope.fallback_count": "Fallback models ({count}): {names}",
    "modelscope.vision_auto": "Vision model auto-configured: {model}",
    "modelscope.vision_unknown": "unknown",

    # ─── Connection test / load error ───
    "connection.testing": "Testing connection...",
    "connection.failed": "Connection test failed: {error}",
    "config.load_failed": "Warning: failed to load {path}: {e}",

    # ─── Tavily ───
    "tavily.detected_env": "Detected TAVILY_API_KEY environment variable, Tavily auto-configured",
    "tavily.configured": "Tavily configured: {key}",
    "tavily.ask_configure": "Configure Tavily search engine?",
    "tavily.skipped": "Skipped, configure later via the /search command",
    "tavily.input_key": "Enter Tavily API Key:",
    "tavily.saved": "Tavily API Key saved and active",

    # ─── LangSmith ───
    "langsmith.detected_env": "Detected LANGSMITH_API_KEY environment variable, LangSmith auto-configured",
    "langsmith.ask_configure": "Configure LangSmith tracing?",
    "langsmith.skipped": "Skipped, configure later via the /langsmith command",
    "langsmith.input_project": "Enter LangSmith project name:",
    "langsmith.input_key": "Enter LangSmith API Key:",
    "langsmith.saved": "LangSmith configuration written to environment variables, takes effect after restart",

    # ─── Common ───
    "common.yes": "Yes",
    "common.no": "No",
    "common.cancelled": "Cancelled",
    "common.back": "Back",

    # ─── Vision model config ───
    "vision.menu": "Vision model config:",
    "vision.view": "View current config",
    "vision.reconfigure": "Reconfigure",
    "vision.switch": "Switch model",
    "vision.configure": "Configure vision model",
    "vision.unconfigured_ask": "Vision model not configured. Configure now?",
    "vision.select_key_source": "Select API Key source:",
    "vision.use_env_token": "Use env var ModelScopeToken ({masked})",
    "vision.manual_key": "Enter API Key manually",
    "vision.input_key": "Enter ModelScope API Key:",
    "vision.select_default": "Select default vision model:",
    "vision.config_done": "Vision model configured: {model} (default)",
    "vision.fallback_count": "Fallback models ({count}): {names}",
    "vision.no_default": "Please configure a default vision model first",
    "vision.no_fallback": "No fallback vision models to switch",
    "vision.select_to_use": "Select a vision model to use:",
    "vision.switch_confirm": "Confirm switch to {model}? Current default will move to fallback list",
    "vision.switched": "Switched to: {model}",
    "vision.not_configured": "Vision model not configured",
    "vision.default_label": "Default vision model:",
    "vision.fallback_table_title": "Fallback vision models",
    "vision.col_model": "Model",
    "vision.col_status": "Status",
    "vision.no_fallback_dim": "No fallback models",
    "vision.unknown": "unknown",

    # ─── Skill management ───
    "skill.menu": "Skill management:",
    "skill.view_installed": "View installed skills",
    "skill.install_new": "Install a new skill",
    "skill.none_installed": "No installed skills found",
    "skill.installed_table_title": "Installed skills",
    "skill.col_name": "Name",
    "skill.col_type": "Type",
    "skill.col_desc": "Description",
    "skill.col_path": "Path",
    "skill.select_to_operate": "Select a skill to operate on:",
    "skill.action_on": "Action on skill '{name}':",
    "skill.view_detail": "View details",
    "skill.delete": "Delete skill",
    "skill.skill_file_not_exist": "Skill file does not exist",
    "skill.detail_title": "Skill: {name}",
    "skill.delete_confirm": "Confirm delete skill '{name}'? This cannot be undone!",
    "skill.deleted": "Skill '{name}' deleted",
    "skill.delete_failed": "Delete failed: {error}",
    "skill.input_archive_path": "Enter skill archive path (.zip/.tar.gz/.tgz):",
    "skill.file_not_exist": "File does not exist",
    "skill.validating": "Validating skill package...",
    "skill.invalid_package": "Invalid skill package, must contain SKILL.md",
    "skill.validate_failed": "Skill package validation failed: {error}",
    "skill.install_error": "Skill installation failed: {error}",
    "skill.select_install_location": "Select install location:",
    "skill.install_project": "Project-level (current workdir)",
    "skill.install_global": "Global-level (user dir)",
    "skill.installing": "Installing...",
    "skill.install_success": "Skill '{name}' installed successfully!",
    "skill.install_failed": "Installation failed",
    "skill.type.project": "Project",
    "skill.type.global": "Global",

    # ─── chat REPL ───
    "chat.empty_group": "(empty message group)",
    "chat.goodbye": "Goodbye!",
    "chat.unknown_command": "Unknown command: {command}, type /help for help",
    "chat.new_session_started": "New session started",
    "chat.status.model_unset": "not set",
    "chat.status.common_mode": "Common mode",
    "chat.status.yolo_mode": "YOLO mode",
    "chat.status.modelscope_quota": "\n<ansicyan>ModelScope daily free quota left: global {total} | model({model}) {model_rl}</ansicyan>",
    "chat.interrupted": "[interrupted]",
    "chat.media_embedded": "[embedded {count} media files]",
    "chat.opening": "Opening: {url}",
    "chat.switching_fallback": "Switching to fallback model: {model}",
    "chat.switched_fallback_retry": "Switched to fallback model, retrying...",
    "chat.switch_failed": "Model switch failed: {error}",
    "chat.no_more_fallback": "No more fallback models available",
    "chat.agent_error": "Agent error: {error}",
    "chat.agent_stopped": "This message stopped unexpectedly",
    "chat.load_conv_failed": "Failed to load conversation: {error}",

    # ─── /model ───
    "cmd.model": "Model management (new/edit/switch)",
    "chat.model.menu": "Model management:",
    "chat.model.new": "New model (/model new)",
    "chat.model.edit": "Edit current model (/model edit)",
    "chat.model.switch": "Switch model (/model switch)",

    # ─── /vision / /skill ───
    "cmd.vision": "Vision model config",
    "cmd.skill": "Skill management",
    "chat.skill.init_first": "Please initialize the workdir first",

    # ─── /tools ───
    "cmd.tools": "Show built-in tools",
    "chat.tools.title": "Built-in tools",
    "chat.tools.native_vision": "Current model supports native vision; images/videos will be embedded directly",
    "chat.tools.disabled": " (disabled)",

    # ─── /history ───
    "cmd.history": "Session history",
    "chat.history.none": "No session history",
    "chat.history.select": "Select a session:",
    "chat.history.operation": "Action:",
    "chat.history.load": "Load this session",
    "chat.history.rename": "Rename this session",
    "chat.history.delete": "Delete this session",
    "chat.history.rename_prompt": "Enter a new name (leave empty to restore default):",
    "chat.history.renamed": "Session renamed",
    "chat.history.delete_confirm": "Delete session {tid}?",
    "chat.history.deleted": "Session deleted",

    # ─── /compress ───
    "cmd.compress": "Compress session",
    "chat.compress.no_model": "Please configure a model first",
    "chat.compress.confirm": "Compress the current session?",
    "chat.compress.working": "Compressing...",
    "chat.compress.failed_prefix": "Session compression failed",
    "chat.compress.failed_detail": "Session compression failed: {error}",
    "chat.compress.failed_no_summary": "Session compression failed: LLM response missing summary field",
    "chat.compress.done_prefix": "Conversation compressed: ",
    "chat.compress.complete": "Session compression complete",
    "chat.compress.error": "Compression failed: {error}",

    # ─── /git ───
    "cmd.git": "Git status",
    "chat.git.unavailable": "Git unavailable: {status}",
    "chat.git.repo_init": "Git repository initialized ({count} checkpoints)",
    "chat.git.repo_not_init": "Git repository not initialized",
    "chat.git.rollback_failed": "Git rollback failed: {error}",

    # ─── /search ───
    "cmd.search": "Configure Tavily search API Key",
    "chat.search.unset": "not configured",
    "chat.search.current_key": "Current Tavily API Key: {key}",
    "chat.search.operation": "Action:",
    "chat.search.configure": "Configure API Key",
    "chat.search.clear": "Clear API Key",
    "chat.search.input_key": "Enter Tavily API Key:",
    "chat.search.cleared": "Tavily API Key cleared",
    "chat.search.saved": "Tavily API Key saved",
    "chat.search.cancelled": "No input, cancelled",

    # ─── /mode ───
    "cmd.mode": "Toggle Common/Yolo mode",
    "chat.mode.select": "Select mode:",
    "chat.mode.common": "Common (manually approve risky actions)",
    "chat.mode.yolo": "Yolo (auto-approve all actions)",
    "chat.mode.switched": "Switched to {mode} mode",

    # ─── /workdir ───
    "cmd.workdir": "Switch workdir",
    "chat.workdir.select": "Select workdir:",
    "chat.workdir.custom": "Custom path...",
    "chat.workdir.custom_prompt": "Enter workdir path: ",
    "chat.workdir.not_exist": "Path does not exist",
    "chat.workdir.current": "Workdir: {path}",

    # ─── /messages ───
    "cmd.messages": "Manage history messages (edit/fork/delete)",
    "chat.messages.no_agent": "Agent not initialized",
    "chat.messages.none": "No messages to manage",
    "chat.messages.select_op": "Select action:",
    "chat.messages.edit": "Edit message",
    "chat.messages.fork": "Fork message",
    "chat.messages.delete": "Delete message",
    "chat.messages.select_delete": "Select message groups to delete (space to select, enter to confirm):",
    "chat.messages.delete_confirm": "Delete {count} message groups?",
    "chat.messages.no_valid": "No valid selection",
    "chat.messages.deleted_groups": "Deleted {count} message groups",
    "chat.messages.edit_hint": "Select a message group to edit (everything after it will be deleted):",
    "chat.messages.fork_hint": "Select the fork point (this group will be kept in the branch):",
    "chat.messages.invalid": "Invalid selection",
    "chat.messages.no_human": "This group has no HumanMessage",
    "chat.messages.edit_confirm": "Edit this message group? Everything after it will be deleted.",
    "chat.messages.loaded_to_input": "Message loaded into the input box; edit and send to regenerate",
    "chat.messages.fork_confirm": "Create a branch from message group #{idx}?",
    "chat.messages.select_new_workdir": "Select a new workdir:",
    "chat.messages.copying": "Copying workdir files...",
    "chat.messages.copy_failed": "Copy failed:\n{tb}",
    "chat.messages.fork_done": "Branch created! Workdir: {path}",

    # ─── copy dir (Windows reserved names etc.) ───
    "chat.copy.skip_reserved": "Skipping Windows reserved name: {name}",
    "chat.copy.dir_failed": "Copy dir failed: {name}, {error}",
    "chat.copy.file_failed": "Copy file failed: {name}, {error}",

    # ─── HITL ───
    "hitl.action": "Action:",
    "hitl.approve": "approve",
    "hitl.reject": "reject",
    "hitl.write_file": "Write file: {path}\nContent: {content}",
    "hitl.edit_modify": "[HITL] edit  modify file: {path}",
    "hitl.user_rejected": "user rejected",

    # ─── /help table ───
    "chat.help.title": "Commands",
    "chat.help.col_cmd": "Command",
    "chat.help.col_desc": "Description",

    # ─── slash command descriptions (rest) ───
    "cmd.new": "New session",
    "cmd.langsmith": "LangSmith tracing",
    "cmd.homepage": "Open project homepage",
    "cmd.help": "Show help",
    "cmd.quit": "Quit",
    "cmd.lang": "选择语言 / Select language",

    # ─── /langsmith (chat command) ───
    "chat.langsmith.state_on": "On",
    "chat.langsmith.state_off": "Off",
    "chat.langsmith.tracing_line": "LangSmith tracing: {state}",
    "chat.langsmith.project_line": "  Project: {project}",
    "chat.langsmith.operation": "Action:",
    "chat.langsmith.open_panel": "Open dashboard",
    "chat.langsmith.enable": "Enable tracing",
    "chat.langsmith.disable": "Disable tracing",
    "chat.langsmith.rename_project": "Rename project",
    "chat.langsmith.change_key": "Change API Key",
    "chat.langsmith.set_key_first": "Please set the LangSmith API Key first",
    "chat.langsmith.input_project": "Enter project name:",
    "chat.langsmith.input_key": "Enter LangSmith API Key:",
    "chat.langsmith.config_updated": "LangSmith config updated, takes effect after restart",

    # ─── Tools (ask_user / web_search / vision) ───
    "tools.tavily_not_configured": "[ERROR] Tavily API Key not configured. Use the /search command to configure it.",
    "tools.please_input": "Please enter: ",
    "tools.user_cancelled": "(user cancelled)",
    "tools.query_failed": "(query failed: {error})",
    "tools.batch_questions": "📋 Batch questions ({count} questions)",
    "tools.question_progress": "Question {i}/{total}: {text}",
    "tools.select_hint": "Select (space to choose, enter to confirm):",
    "tools.batch_results": "=== Batch Question Results ===",
    "tools.batch_qa": "Question: {question}\nAnswer: {answer}",
    "tools.vision_not_configured": "vision:\n[FAILED] Vision model not configured.\nUse the /vision command to configure the ModelScope API Key,\nor set the ModelScopeToken environment variable.",
    "tools.vision_call_failed": "Vision model {model} call failed: {error}",
    "tools.vision_all_failed": "vision:\n[FAILED] All vision models failed\nLast error: {error}",

    # ─── agent_setup retry/fallback ───
    "agent.vision_native_filter": "The current model supports native vision; image/video is already embedded in the message, so the vision tool is not needed. Please analyze the image/video content in the message directly.",
    "agent.switch_to_fallback": "Main model failed after {count} retries, switching to fallback model...",
    "agent.no_fallback_giveup": "Request failed, no fallback model available, giving up\n  {error}",
    "agent.retry_in": "Request failed ({count}/{max}), retrying in {delay}s...\n  {error}",
    "agent.switch_error": "switching to fallback model",

    # ─── runner ───
    "runner.fallback_switched": "Agent {type} main model failed, switched to fallback model, please retry",

    # ─── display welcome / spinner ───
    "display.welcome_hint": "Enter to send | Ctrl+Enter for newline | /help for commands\nCtrl+C to interrupt | Tab to toggle mode | /quit to exit",
    "display.organizing": "Organizing results...",

    # ─── git_checker ───
    "git.available": "Git available",
    "git.cmd_failed": "Git command failed: {error}",
    "git.unknown_error": "unknown error",
    "git.not_found": "Git command not found. Please ensure Git is installed and added to PATH",
    "git.timeout": "Git command timed out",
    "git.exception": "Git check exception: {error}",

    # ─── cli ───
    "cli.init_failed": "Initialization failed",
    "cli.unknown_action": "Unknown action: {action}",
    "cli.available_actions": "Available actions: new, edit, switch",
    "cli.opening": "Opening: {url}",

    # ─── prompts / form ───
    "prompt.skip": "Skip (not set)",
    "prompt.custom_input": "Custom input...",
    "prompt.please_input": "Please enter: ",
    "form.model_name": "Enter model name: ",
    "form.base_url": "Enter API Base URL:",
    "form.api_key_source": "Select API Key source:",
    "form.keep_current_key": "Keep current key ({masked})",
    "form.reinput_key": "Re-enter API Key...",
    "form.input_key": "Enter API Key: ",
    "form.api_key_empty": "API Key cannot be empty",
    "form.configure_hyperparams": "Configure hyperparameters?",
    "form.input_temperature": "Enter temperature: ",
    "form.input_top_p": "Enter top_p: ",
    "form.input_top_k": "Enter top_k: ",
    "form.input_max_tokens": "Enter max_completion_tokens: ",
    "form.input_stop": "Enter stop sequences (comma-separated): ",
    "form.input_freq_penalty": "Enter frequency_penalty: ",
    "form.input_presence_penalty": "Enter presence_penalty: ",
    "modelscope.detected_token": "ModelScope token detected. Use it?",
    "modelscope.manual_input": "Manual input...",
    "modelscope.input_key": "Enter ModelScope API Key: ",
    "provider.bigmodel": "Zhipu GLM",
    "provider.qwen": "Qwen",
}
