"""中文文案。随 Phase 2/3 逐步扩充。注意：选项类字符串须与历史完全一致（测试 mock 依赖）。"""

MESSAGES = {
    # ─── 语言选择（双语展示，两个 catalog 相同）───
    "lang.saved_zh": "已设置语言：中文",
    "lang.saved_en": "Language set to: English",

    # ─── 首次运行向导 ───
    "firstrun.panel": "[bold]ChCode[/bold] — 终端 AI 编程助手\n\n首次运行需要配置 AI 模型连接。\n设置环境变量后可自动检测（推荐），或手动填写配置。",
    "firstrun.select_method": "选择配置方式:",
    "firstrun.env_detected": "{name} (检测到 {env_var})",
    "firstrun.modelscope_quick": "魔搭快捷配置...",
    "firstrun.manual": "手动配置...",
    "firstrun.exit": "退出",
    "firstrun.exit_hint": "设置环境变量后重新运行，或执行 chcode config new 手动配置",
    "firstrun.no_env_key": "未检测到环境变量中的 API Key",
    "firstrun.select": "选择:",
    "firstrun.env_hint": "提示: 在环境变量中设置 API Key 后重新运行，例如:",
    "firstrun.env_example": "  set BIGMODEL_API_KEY=your_key",
    "firstrun.manual_cmd_hint": "或执行 chcode config new 手动配置",
    "firstrun.config_done": "配置完成: {model}",

    # ─── 模型配置 ───
    "model.method_select": "配置方式:",
    "model.context_length": "上下文长度（token 数，默认 1M）:",
    "model.saved": "模型配置已保存: {model}",
    "model.multimodal_ask": "该模型是否为多模态（视觉）模型？",
    "model.vision_added_default": "已加入视觉模型清单(默认): {model}（图片将直接处理、vision 工具将停用）",
    "model.vision_added_fallback": "已加入视觉模型清单(备用): {model}（图片将直接处理、vision 工具将停用）",
    "model.vision_duplicate": "未写入视觉配置（已存在相同配置）",
    "model.vision_failed": "视觉模型配置失败（不影响主配置）: {error}",
    "model.edit_none": "没有当前模型配置，请新建",
    "model.updated": "模型配置已更新: {model}",
    "model.switch_no_default": "请先配置默认模型",
    "model.switch_no_fallback": "没有备用模型可切换",
    "model.current_default_tag": " (当前默认)",
    "model.select_to_use": "选择要使用的模型:",
    "model.switch_confirm": "确定切换到 {model}？当前默认将移至备用列表",
    "model.switched": "已切换到: {model}",

    # ─── ModelScope 快捷配置 ───
    "modelscope.testing": "测试连接中...",
    "modelscope.connect_failed": "连接测试失败: {detail}",
    "modelscope.config_done": "配置完成: {model} (默认)",
    "modelscope.fallback_count": "备用模型 ({count} 个): {names}",
    "modelscope.vision_auto": "视觉模型已自动配置: {model}",
    "modelscope.vision_unknown": "未知",

    # ─── 连接测试 / 加载错误 ───
    "connection.testing": "测试连接中...",
    "connection.failed": "连接测试失败: {error}",
    "config.load_failed": "Warning: 加载 {path} 失败: {e}",

    # ─── Tavily ───
    "tavily.detected_env": "检测到 TAVILY_API_KEY 环境变量，已自动配置 Tavily",
    "tavily.configured": "已配置 Tavily: {key}",
    "tavily.ask_configure": "是否配置 Tavily 搜索引擎?",
    "tavily.skipped": "已跳过，后续可通过 /search 命令配置",
    "tavily.input_key": "请输入 Tavily API Key:",
    "tavily.saved": "Tavily API Key 已保存并生效",

    # ─── LangSmith ───
    "langsmith.detected_env": "检测到 LANGSMITH_API_KEY 环境变量，已自动配置 LangSmith",
    "langsmith.ask_configure": "是否配置 LangSmith 追踪?",
    "langsmith.skipped": "已跳过，后续可通过 /langsmith 命令配置",
    "langsmith.input_project": "请输入 LangSmith 项目名称:",
    "langsmith.input_key": "请输入 LangSmith API Key:",
    "langsmith.saved": "LangSmith 配置已写入环境变量，重启后生效",

    # ─── 通用 ───
    "common.yes": "是",
    "common.no": "否",
    "common.cancelled": "已取消",
    "common.back": "返回",

    # ─── 视觉模型配置 ───
    "vision.menu": "视觉模型配置:",
    "vision.view": "查看当前配置",
    "vision.reconfigure": "重新配置",
    "vision.switch": "切换模型",
    "vision.configure": "配置视觉模型",
    "vision.unconfigured_ask": "视觉模型未配置，是否现在配置？",
    "vision.select_key_source": "选择 API Key 来源:",
    "vision.use_env_token": "使用环境变量 ModelScopeToken ({masked})",
    "vision.manual_key": "手动输入 API Key",
    "vision.input_key": "输入 ModelScope API Key:",
    "vision.select_default": "选择默认视觉模型:",
    "vision.config_done": "视觉模型配置完成: {model} (默认)",
    "vision.fallback_count": "备用模型 ({count} 个): {names}",
    "vision.no_default": "请先配置默认视觉模型",
    "vision.no_fallback": "没有备用视觉模型可切换",
    "vision.select_to_use": "选择要使用的视觉模型:",
    "vision.switch_confirm": "确定切换到 {model}？当前默认将移至备用列表",
    "vision.switched": "已切换到: {model}",
    "vision.not_configured": "未配置视觉模型",
    "vision.default_label": "默认视觉模型:",
    "vision.fallback_table_title": "备用视觉模型",
    "vision.col_model": "模型",
    "vision.col_status": "状态",
    "vision.no_fallback_dim": "无备用模型",
    "vision.unknown": "未知",

    # ─── 技能管理 ───
    "skill.menu": "技能管理:",
    "skill.view_installed": "查看已安装技能",
    "skill.install_new": "安装新技能",
    "skill.none_installed": "没有发现已安装的技能",
    "skill.installed_table_title": "已安装技能",
    "skill.col_name": "名称",
    "skill.col_type": "类型",
    "skill.col_desc": "描述",
    "skill.col_path": "路径",
    "skill.select_to_operate": "选择技能进行操作:",
    "skill.action_on": "对技能 '{name}' 的操作:",
    "skill.view_detail": "查看详情",
    "skill.delete": "删除技能",
    "skill.skill_file_not_exist": "技能文件不存在",
    "skill.detail_title": "技能: {name}",
    "skill.delete_confirm": "确定删除技能 '{name}'？此操作不可撤销！",
    "skill.deleted": "技能 '{name}' 已删除",
    "skill.delete_failed": "删除失败: {error}",
    "skill.input_archive_path": "输入技能压缩包路径 (.zip/.tar.gz/.tgz):",
    "skill.file_not_exist": "文件不存在",
    "skill.validating": "验证技能包...",
    "skill.invalid_package": "无效的技能包，必须包含 SKILL.md",
    "skill.validate_failed": "验证技能包失败: {error}",
    "skill.install_error": "安装技能失败: {error}",
    "skill.select_install_location": "选择安装位置:",
    "skill.install_project": "项目级 (当前工作目录)",
    "skill.install_global": "全局级 (用户目录)",
    "skill.installing": "安装中...",
    "skill.install_success": "技能 '{name}' 安装成功！",
    "skill.install_failed": "安装失败",
    "skill.type.project": "项目",
    "skill.type.global": "全局",

    # ─── chat REPL ───
    "chat.empty_group": "(空消息组)",
    "chat.goodbye": "再见！",
    "chat.unknown_command": "未知命令: {command}，输入 /help 查看帮助",
    "chat.new_session_started": "新会话已开始",
    "chat.status.model_unset": "未设置",
    "chat.status.common_mode": "普通模式",
    "chat.status.yolo_mode": "YOLO 模式",
    "chat.status.modelscope_quota": "\n<ansicyan>魔搭今日免费额度剩余: 全局 {total} │ 模型({model}) {model_rl}</ansicyan>",
    "chat.interrupted": "[已中断]",
    "chat.media_embedded": "[已嵌入 {count} 个媒体文件]",
    "chat.opening": "正在打开: {url}",
    "chat.switching_fallback": "正在切换到备用模型: {model}",
    "chat.switched_fallback_retry": "已切换到备用模型，自动重试中...",
    "chat.switch_failed": "切换模型失败: {error}",
    "chat.no_more_fallback": "没有更多备用模型可用",
    "chat.agent_error": "Agent 执行错误: {error}",
    "chat.agent_stopped": "该消息意外停止",
    "chat.load_conv_failed": "加载对话失败: {error}",

    # ─── /model ───
    "cmd.model": "模型管理（新建/编辑/切换）",
    "chat.model.menu": "模型管理:",
    "chat.model.new": "新建模型 (/model new)",
    "chat.model.edit": "编辑当前模型 (/model edit)",
    "chat.model.switch": "切换模型 (/model switch)",

    # ─── /vision / /skill ───
    "cmd.vision": "视觉模型配置",
    "cmd.skill": "技能管理",
    "chat.skill.init_first": "请先初始化工作目录",

    # ─── /tools ───
    "cmd.tools": "显示内置工具",
    "chat.tools.title": "内置工具",
    "chat.tools.native_vision": "当前模型支持原生视觉，图片/视频将直接嵌入消息",
    "chat.tools.disabled": " (已禁用)",

    # ─── /history ───
    "cmd.history": "历史会话",
    "chat.history.none": "没有历史会话",
    "chat.history.select": "选择历史会话:",
    "chat.history.operation": "操作:",
    "chat.history.load": "加载此会话",
    "chat.history.rename": "重命名此会话",
    "chat.history.delete": "删除此会话",
    "chat.history.rename_prompt": "输入新名称（留空恢复默认）:",
    "chat.history.renamed": "会话已重命名",
    "chat.history.delete_confirm": "确定删除会话 {tid}？",
    "chat.history.deleted": "会话已删除",

    # ─── /compress ───
    "cmd.compress": "压缩会话",
    "chat.compress.no_model": "请先配置模型",
    "chat.compress.confirm": "确定压缩当前会话？",
    "chat.compress.working": "压缩中...",
    "chat.compress.failed_prefix": "会话压缩失败",
    "chat.compress.failed_detail": "会话压缩失败: {error}",
    "chat.compress.failed_no_summary": "会话压缩失败: LLM 返回结果缺少 summary 字段",
    "chat.compress.done_prefix": "历史对话已压缩: ",
    "chat.compress.complete": "会话压缩完成",
    "chat.compress.error": "压缩失败: {error}",

    # ─── /git ───
    "cmd.git": "Git 状态",
    "chat.git.unavailable": "Git 不可用: {status}",
    "chat.git.repo_init": "Git 仓库已初始化 ({count} 个检查点)",
    "chat.git.repo_not_init": "Git 仓库未初始化",
    "chat.git.rollback_failed": "Git 回滚失败: {error}",

    # ─── /search ───
    "cmd.search": "配置 Tavily 搜索 API Key",
    "chat.search.unset": "未配置",
    "chat.search.current_key": "当前 Tavily API Key: {key}",
    "chat.search.operation": "操作:",
    "chat.search.configure": "配置 API Key",
    "chat.search.clear": "清除 API Key",
    "chat.search.input_key": "请输入 Tavily API Key:",
    "chat.search.cleared": "Tavily API Key 已清除",
    "chat.search.saved": "Tavily API Key 已保存",
    "chat.search.cancelled": "未输入，已取消",

    # ─── /mode ───
    "cmd.mode": "切换 Common/Yolo 模式",
    "chat.mode.select": "选择模式:",
    "chat.mode.common": "Common (手动批准风险操作)",
    "chat.mode.yolo": "Yolo (自动批准所有操作)",
    "chat.mode.switched": "已切换到 {mode} 模式",

    # ─── /workdir ───
    "cmd.workdir": "切换工作目录",
    "chat.workdir.select": "选择工作目录:",
    "chat.workdir.custom": "自定义路径...",
    "chat.workdir.custom_prompt": "请输入工作目录路径: ",
    "chat.workdir.not_exist": "路径不存在",
    "chat.workdir.current": "工作目录: {path}",

    # ─── /messages ───
    "cmd.messages": "管理历史消息（编辑/分叉/删除）",
    "chat.messages.no_agent": "Agent 未初始化",
    "chat.messages.none": "没有可管理的消息",
    "chat.messages.select_op": "选择操作:",
    "chat.messages.edit": "编辑消息",
    "chat.messages.fork": "分叉消息",
    "chat.messages.delete": "删除消息",
    "chat.messages.select_delete": "选择要删除的消息组（空格选择，回车确认）:",
    "chat.messages.delete_confirm": "确定删除 {count} 个消息组？",
    "chat.messages.no_valid": "没有有效的选择",
    "chat.messages.deleted_groups": "已删除 {count} 个消息组",
    "chat.messages.edit_hint": "选择要编辑的消息组（编辑后将删除此消息组之后的所有内容）:",
    "chat.messages.fork_hint": "选择 Fork 点（此消息组将保留在分支中）:",
    "chat.messages.invalid": "无效的选择",
    "chat.messages.no_human": "该组没有 HumanMessage",
    "chat.messages.edit_confirm": "确定编辑此消息组？编辑后将删除此消息组之后的所有内容。",
    "chat.messages.loaded_to_input": "消息已加载到输入框，修改后发送即可重新生成",
    "chat.messages.fork_confirm": "确定从第 {idx} 条消息组创建分支？",
    "chat.messages.select_new_workdir": "选择新工作目录:",
    "chat.messages.copying": "复制工作目录文件...",
    "chat.messages.copy_failed": "复制文件失败:\n{tb}",
    "chat.messages.fork_done": "分支已创建！工作目录: {path}",

    # ─── 复制目录（Windows 保留名等）───
    "chat.copy.skip_reserved": "跳过 Windows 保留名: {name}",
    "chat.copy.dir_failed": "复制目录失败: {name}, {error}",
    "chat.copy.file_failed": "复制文件失败: {name}, {error}",

    # ─── HITL ───
    "hitl.action": "操作:",
    "hitl.approve": "approve (批准)",
    "hitl.reject": "reject (拒绝)",
    "hitl.write_file": "写入文件: {path}\n内容: {content}",
    "hitl.edit_modify": "[HITL] edit  修改文件: {path}",
    "hitl.user_rejected": "用户已拒绝",

    # ─── /help 表格 ───
    "chat.help.title": "命令列表",
    "chat.help.col_cmd": "命令",
    "chat.help.col_desc": "说明",

    # ─── 斜杠命令描述（其余）───
    "cmd.new": "新会话",
    "cmd.langsmith": "LangSmith 追踪",
    "cmd.homepage": "打开项目主页",
    "cmd.help": "显示帮助",
    "cmd.quit": "退出",
    "cmd.lang": "选择语言 / Select language",

    # ─── /langsmith（chat 命令）───
    "chat.langsmith.state_on": "开启",
    "chat.langsmith.state_off": "关闭",
    "chat.langsmith.tracing_line": "LangSmith 追踪: {state}",
    "chat.langsmith.project_line": "  项目: {project}",
    "chat.langsmith.operation": "操作:",
    "chat.langsmith.open_panel": "打开面板",
    "chat.langsmith.enable": "开启追踪",
    "chat.langsmith.disable": "关闭追踪",
    "chat.langsmith.rename_project": "修改项目名称",
    "chat.langsmith.change_key": "修改 API Key",
    "chat.langsmith.set_key_first": "请先设置 LangSmith API Key",
    "chat.langsmith.input_project": "请输入项目名称:",
    "chat.langsmith.input_key": "请输入 LangSmith API Key:",
    "chat.langsmith.config_updated": "LangSmith 配置已更新，重启后生效",

    # ─── 工具（ask_user / web_search / vision）───
    "tools.tavily_not_configured": "[ERROR] Tavily API Key 未配置，请使用 /search 命令配置",
    "tools.please_input": "请输入: ",
    "tools.user_cancelled": "(用户取消)",
    "tools.query_failed": "(询问失败: {error})",
    "tools.batch_questions": "📋 批量提问 ({count} 个问题)",
    "tools.question_progress": "问题 {i}/{total}: {text}",
    "tools.select_hint": "选择（空格选择，回车确认）:",
    "tools.batch_results": "=== 批量提问结果 ===",
    "tools.batch_qa": "问题: {question}\n回答: {answer}",
    "tools.vision_not_configured": "vision:\n[FAILED] 视觉模型未配置。\n请使用 /vision 命令配置 ModelScope API Key，\n或设置环境变量 ModelScopeToken。",
    "tools.vision_call_failed": "视觉模型 {model} 调用失败: {error}",
    "tools.vision_all_failed": "vision:\n[FAILED] 所有视觉模型均调用失败\n最后错误: {error}",

    # ─── agent_setup 重试/回退 ───
    "agent.vision_native_filter": "当前模型支持原生视觉，图片/视频已直接嵌入消息，无需调用 vision 工具。请直接分析消息中的图片/视频内容。",
    "agent.switch_to_fallback": "主模型重试{count}次失败，切换到备用模型...",
    "agent.no_fallback_giveup": "请求失败，无备用模型可用，放弃请求\n  {error}",
    "agent.retry_in": "请求失败 ({count}/{max}), {delay}秒后重试...\n  {error}",
    "agent.switch_error": "切换到备用模型",

    # ─── runner ───
    "runner.fallback_switched": "Agent {type} 主模型失败，已切换备用模型，请重试",

    # ─── display 欢迎页 / spinner ───
    "display.welcome_hint": "Enter 发送 | Ctrl+Enter 换行 | /help 查看命令\nCtrl+C 中断生成 | Tab 切换模式 | /quit 退出",
    "display.organizing": "正在整理结果...",

    # ─── git_checker ───
    "git.available": "Git可用",
    "git.cmd_failed": "Git命令执行失败: {error}",
    "git.unknown_error": "未知错误",
    "git.not_found": "未找到Git命令，请确保Git已安装并添加到PATH环境变量中",
    "git.timeout": "Git命令执行超时",
    "git.exception": "检查Git时发生异常: {error}",

    # ─── cli ───
    "cli.init_failed": "初始化失败",
    "cli.unknown_action": "未知操作: {action}",
    "cli.available_actions": "可用操作: new, edit, switch",
    "cli.opening": "正在打开: {url}",

    # ─── prompts / 表单 ───
    "prompt.skip": "跳过 (不设置)",
    "prompt.custom_input": "自定义输入...",
    "prompt.please_input": "请输入: ",
    "form.model_name": "输入模型名称: ",
    "form.base_url": "输入 API Base URL:",
    "form.api_key_source": "选择 API Key 来源:",
    "form.keep_current_key": "保持当前 Key ({masked})",
    "form.reinput_key": "重新输入 API Key...",
    "form.input_key": "输入 API Key: ",
    "form.api_key_empty": "API Key 不能为空",
    "form.configure_hyperparams": "配置超参数？",
    "form.input_temperature": "输入 temperature: ",
    "form.input_top_p": "输入 top_p: ",
    "form.input_top_k": "输入 top_k: ",
    "form.input_max_tokens": "输入 max_completion_tokens: ",
    "form.input_stop": "输入停止序列 (逗号分隔): ",
    "form.input_freq_penalty": "输入 frequency_penalty: ",
    "form.input_presence_penalty": "输入 presence_penalty: ",
    "modelscope.detected_token": "检测到 ModelScope Token，是否使用？",
    "modelscope.manual_input": "手动输入...",
    "modelscope.input_key": "输入 ModelScope API Key: ",
    "provider.bigmodel": "智谱 GLM",
    "provider.qwen": "通义千问",
}
